db.restaurants.find();
db.restaurants.find({}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1});
db.restaurants.find({}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1, _id: 0});
db.restaurants.find({}, {restaurant_id: 1, name: 1, borough: 1, address: {zipcode: 1}, _id: 0});
db.restaurants.find({borough: "Bronx"});
db.restaurants.find({borough: "Bronx"}).limit(5);
db.restaurants.find({borough: "Bronx"}).skip(5).limit(5);
db.restaurants.find({'grades.score': {$gt: 90}});
db.restaurants.find({'grades.score': {$gt: 80, $lt: 100}});
db.restaurants.find({'address.coord.0': {$lt: -95.754168}});
db.restaurants.find({'address.coord.0': {$lt: -65.754168}, 'grades.score': {$gt: 90}, cuisine: {$ne: 'American '}}  );
db.restaurants.find({'address.coord.0': {$lt: -65.754168}, 'grades.score': {$gt: 90}, cuisine: {$ne: 'American '}}  );
db.restaurants.find({'grades.grade': "A", cuisine: {$ne: 'American '}, borough: {$ne: "Brooklyn"}}).sort({borough: 1});
db.restaurants.find({name: {$regex: "^Wil"}}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1, _id: 0});
db.restaurants.find({name: {$regex: "ces$"}}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1, _id: 0});
db.restaurants.find({name: {$regex: "Reg"}}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1, _id: 0});
db.restaurants.find({borough: "Bronx", cuisine: {$in: ["American", "Chinese"]}});
db.restaurants.find({borough: {$in: ["Bronx", "Queens", "Staten Island", "Brooklyn"]}}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1, _id: 0});
db.restaurants.find({borough: {$not: {$in: ["Bronx", "Queens", "Staten Island", "Brooklyn"]}}}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1, _id: 0});
db.restaurants.find({'grades.score': {$lt: 10}}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1, _id: 0});
db.restaurants.find({cuisine: {$regex: 'Seafood'}, $or:[{cusine: {$not:{$in: ["American ", "Chinese"]}}}, {name:{$not:{$regex: "^Wil"}}}]}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1, _id: 0});
db.restaurants.find({"grades":{$elemMatch:{grade:"A",score:11,date:ISODate("2014-08-11T00:00:00Z")}}}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1, _id: 0});
db.restaurants.find({"grades.1.grade":"A","grades.1.score":9,"grades.1.date":ISODate("2014-08-11T00:00:00Z")}, {restaurant_id: 1, name: 1, borough: 1, cuisine: 1, _id: 0});
db.restaurants.find({'address.coord.1':{$gt:43,$lte:52}}, {restaurant_id: 1, name: 1, 'address.street': 1, 'address.coord': 1, _id: 0});
db.restaurants.find().sort({name: 1});
db.restaurants.find().sort({name: -1});
db.restaurants.find().sort({name: 1, borough: -1});
db.restaurants.find({'address.street': {$exists: true, $ne: [] }});
db.restaurants.find({'address.coord.0': {$type: 1},'address.coord.1': {$type: 1}})
db.restaurants.find({'grades.score': {$mod: [7, 0 ]}}, {restaurant_id: 1, name: 1, grades: 1, _id: 0});
db.restaurants.find({name: {$regex: "mon"}}, {name: 1, borough: 1, 'address.coord': 1, cusine: 1, _id: 0});
db.restaurants.find({name: {$regex: "^Mad"}}, {name: 1, borough: 1, 'address.coord': 1, cusine: 1, _id: 0});
